title: Elliot Sime
description: My Personal Blog
author: Elliot Sime
logo: static/img/avatar.png
github: https://github.com/eksime
about: 

baseurl: ""
url: "https://eksime.github.io"

disqus_shortname: aboutashu
google_analytics: UA-72862926-1

share:
  twitter_username: \#ElliotSime
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
