# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            eksime
tagline:          'A Jekyll theme'
description:      'My personal site for info/projects'
url:              https://eksi.me
baseurl:          /

author:
  name:           'Elliot Sime'
  url:            https://twitter.com/ElliotSime

paginate:         5

# Custom vars
version:          2.1.0

github:
  url:           https://github.com/eksime
  repo:           https://github.com/eksime/eksime.github.io
